### ISSUE TITLE
DOD: Usage Stats Tracking 

### ISSUE THREAD

**Issue by kjgarza** [datacite/tasks#113]
# DOD: Usage Stats Tracking 

To complete this DOD, the lead developer that coded the feature needs to review and validate every item in the "Development checklist" has been completed and its working correctly. Note: automated test are not enough to tell a feature is working correctly. 
After the "Development checklist" is completed the designer must review and validated every item in the "Product Engineering Checklist".

### Development Checklist
- [ ] Passed through peer review see Pull Request Guidelines
- [ ] Unit, integration, and system tests that all pass on the CI.
- [ ] Regressions and bugs are covered (where relevant) with tests that reduce the risk of the issue happening again.
- [ ] Reviewed by relevant reviewers and all comments are addressed.
- [ ] Confirmed to be working in the stage environment with no new Sentry errors.
- [ ] Write an ADR (when relevant).
- [ ] Confirmed that user stories are met:
    - [ ] 1.1 Scenario: Activating the Usage stats tracking
    - [ ] ~~1.2 Scenario: Getting the Usage stats tracker snippet in Fabrica~~
    - [ ] ~~Scenario: Deactivating the Usage stats tracking ~~
    - [ ] 3.1 Scenario: Receiving usage stats from the Tracker for existing DataCite DOIs
    - [ ] Scenario: Displaying Usage Stats from Tracker in the REST API
    - [ ] Scenario: Displaying Usage Stats from Tracker in the GraphQL API
    - [ ] Scenario: Displaying Usage Stats from Tracker in the Data metrics badge
    - [ ] Scenario: Displaying Usage Stats from Tracker in the EventData API
    - [ ] Scenario: Displaying Usage Stats from Tracker in SUSHI Reports
    - [ ] As a repository admin, I would like the collected usage stats to be available, in the different interfaces, within 10 days after the end of the month of collection.
   

### Product Engineering Checklist
- [ ] Confirmed that user stories are met:
    - [ ] 1.1 Scenario: Activating the Usage stats tracking
    - [ ] ~~1.2 Scenario: Getting the Usage stats tracker snippet in Fabrica~~
    - [ ]  ~~Scenario: Deactivating the Usage stats tracking~~
    - [ ] 3.1 Scenario: Receiving usage stats from the Tracker for existing DataCite DOIs
    - [ ] Scenario: Displaying Usage Stats from Tracker in the REST API
    - [ ] Scenario: Displaying Usage Stats from Tracker in the GraphQL API
    - [ ] Scenario: Displaying Usage Stats from Tracker in the Data metrics badge
    - [ ] Scenario: Displaying Usage Stats from Tracker in the EventData API
    - [ ] Scenario: Displaying Usage Stats from Tracker in SUSHI Reports
    - [ ] As a repository admin, I would like the collected usage stats to be available, in the different interfaces, within 10 days after the end of the month of collection.
   

- [ ] Feature Flag has been removed. (where relevant)
